# Generated by Django 5.2.9 on 2026-01-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
