# Generated by Django 5.2.9 on 2026-01-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ingredient_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/'),
        ),
    ]
