# Generated by Django 5.2.9 on 2026-01-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_productoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOption',
        ),
    ]
